### ISSUE TITLE
GitHub Actions - deprecated warnings found - action required!

### ISSUE THREAD

**Issue by sarahethompson** [hashicorp/terraform-cloud-operator#176]
Workflow Name: build
Branch: main
Run URL: https://github.com/hashicorp/terraform-cloud-operator/actions/runs/4961732057

save-state deprecation warnings: 0
set-output deprecation warnings: 0
node12 deprecation warnings: 1

Please review these deprecation warnings as soon as possible and merge in the necessary updates.

GitHub will be removing support for these commands and plan to fully disable them on 31st May 2023. At this time, any workflow that still utilizes these commands will fail. See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.

GitHub have not finalized a date for deprecating node12 yet but have indicated that this will be summer 2023. So it is advised to switch to node16 asap. See https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

If you need any help, please reach out to us in #team-rel-eng.

**Comment by arybolovlev** [comment]
Hi @sarahethompson,

It looks like this is coming from the **_hashicorp/actions-docker-build_** GHA.

In our `build.yml` workflow we use the latest released version `1.3.4` that uses `actions/download-artifact@v2` and `actions/upload-artifact@v2`: https://github.com/hashicorp/actions-docker-build/blob/v1.3.4/action.yml. It seems to be addresses in [`1.3.5`](https://github.com/hashicorp/actions-docker-build/blob/v1.3.5/action.yml) which is in the _pre-release_ stage now: https://github.com/hashicorp/actions-docker-build/releases.

Should we update the `build` workflow to use `1.3.5`(pre-release) or wait till it goes to release?

Thank you!

**Comment by sarahethompson** [comment]
Hey @arybolovlev - I see you've already bumped this to 1.5.0, this is correct! I don't think we are creating releases anymore, just pushing tags. We can make sure to create releases in the future to make this less confusing!
