### ISSUE TITLE
🐛 Unable to start terraform-cloud-operator pods: "exec /manager: exec format error"

### ISSUE THREAD

**Issue by KamalAman** [hashicorp/terraform-cloud-operator#193]
### Operator Version, Kind and Kubernetes Version
 - Operator version: beta-6
 - Kind: Workspace
 - Kubernetes version: v1.25.6
 - Platform: AKS

### YAML Manifest File
```yaml
 None
```

### Output Log

```
exec /manager: exec format error
```

### Steps To Reproduce

```tf
resource "kubernetes_namespace" "tfc-operator-system" {
  metadata {
    name = "tfc-operator-system"
  }
}

resource "kubernetes_secret" "terraformrc" {
  metadata {
    name      = "terraformrc"
    namespace = kubernetes_namespace.tfc-operator-system.metadata[0].name
  }

  data = {
    "token" = var.TFE_TEAM_TOKEN
  }
}

resource "helm_release" "tfc-operator" {
  name    = "terraform-operator"
  chart   = "oci://public.ecr.aws/t8q4c9g6/terraform-cloud-operator"
  version = "0.0.7"

  namespace        = kubernetes_namespace.tfc-operator-system.metadata[0].name
  create_namespace = false

  set {
    name  = "operator.image.repository"
    value = "public.ecr.aws/t8q4c9g6/terraform-cloud-operator"
  }

  set {
    name  = "operator.image.tag"
    value = "2.0.0-beta6"
  }
}
```

### Expected Behavior
What should have happened?

* Operator should be successfully installed 

### Actual Behavior
What actually happened?

* Operator image throw the following error when initializing `exec /manager: exec format error`

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Comment by arybolovlev** [comment]
Hi @KamalAman,

Thank you for reporting this issue. Could you please tell me on which platform(amd64, arm64, etc) you run the operator?

From what I can see, the Docker image was built only for `arm64`:

```console
$ docker image inspect public.ecr.aws/t8q4c9g6/terraform-cloud-operator:2.0.0-beta6 | jq '.[].Architecture'

"arm64"
```

Another thing that confuses me is the version you use. The `2.0.0-beta6` was not yet [released](https://github.com/hashicorp/terraform-cloud-operator/blob/main/CHANGELOG.md#200-beta6-unreleased), though, the image is available(I don't know why).

Thanks!

**Comment by KamalAman** [comment]
Hi @arybolovlev,

I tried with both beta5 and beta6 with both have the same result. Yeah I thought it was strange that i didn't see beta6 as a release on the Github. The reason why I left it as beta6 is because that is what is documented here https://developer.hashicorp.com/terraform/tutorials/kubernetes/kubernetes-operator-v2

Yeah AKS runs under amd64 by default
<img width="572" alt="image" src="https://github.com/hashicorp/terraform-cloud-operator/assets/2692357/7bffcea9-24f4-450d-b86a-f18399e83f9c">

Is is possible for you to update the build pipeline and publish an amd64 container?

Thanks!!

**Comment by magdyksaleh** [comment]
Running into this issue as well trying to run the operator within the kubernetes cluster. Would it be possible to get support for x86 architecture for beta4/beta5?

**Comment by KamalAman** [comment]
As an temporary workaround until this is resolved you can build the container and publish it to your own repo

Just clone this repo and execute the build. 

```
docker build --platform linux/amd64 -t ${ORG}/terraform-cloud-operator:2.0.0-beta6 .
```

**Comment by KamalAman** [comment]
Amazing to see the progress on that PR ^, I can't wait for the next release so we can test :)

**Comment by KamalAman** [comment]
@arybolovlev is there any way we could get a new version with this fix in it? 
Much appreciated!

**Comment by arybolovlev** [comment]
Hi @KamalAman,

`2.0.0-beta7` is available. We have also updated the Helm chart version to align with the Operator version.

By default, Helm does not display development versions (alpha, beta, and release candidate releases). In order to list them, use the following command when looking for available versions:

```console
$ helm search repo hashicorp/terraform-cloud-operator --versions --devel
```

Please, use the option `--version VERSION` with `helm install` and `helm upgrade` commands to specify the version you want to install:

```console
$ helm install demo hashicorp/terraform-cloud-operator --version 2.0.0-beta7
```

Thank you!

**Comment by KamalAman** [comment]
Great, it works with the updated terraform helm_release configuration below 

```tf
resource "helm_release" "tfc-operator" {
  name       = "terraform-operator"
  chart      = "terraform-cloud-operator"
  version    = "2.0.0-beta7"
  repository = "https://helm.releases.hashicorp.com"

  namespace        = kubernetes_namespace.tfc-operator-system.metadata[0].name
  create_namespace = false

  set {
    name  = "operator.image.tag"
    value = "2.0.0-beta7"
  }
}
```

You'll want to update the documentation here https://developer.hashicorp.com/terraform/tutorials/kubernetes/kubernetes-operator-v2. I also noticed that there isn't a terraform example in this repo, I think it would be a good be great to include on in this repo. 

Thanks,
