### ISSUE TITLE
🐛  sshKey name not found

### ISSUE THREAD

**Issue by diepes** [hashicorp/terraform-cloud-operator#235]
### Operator Version, Kind and Kubernetes Version
 - Operator version:  From k8s Helm Releases - image: "hashicorp/terraform-cloud-operator:2.0.0-beta7"
 - Kind: Workspace | Module. ? Workspace ?
 - Kubernetes version: "v1.27.1"

### YAML Manifest File
```yaml
# Copy-paste your YAML manifest here
apiVersion: app.terraform.io/v1alpha2
kind: Workspace
...
spec:
  ...
  sshKey: 
    name: git-terraform
...
```

### Output Log

2023-08-03T04:32:32Z    INFO    Reconcile SSH Key       {"workspace": {"name":"playground","namespace":"dev"}, "msg": "getting ssh key ID by name"}
2023-08-03T04:32:32Z    ERROR   Reconcile SSH Key       {"workspace": {"name":"playground","namespace":"dev"}, "msg": "failed to assign ssh key ID", "error": "ssh key ID was not found for ssh key name \"git-terraform\""}
2023-08-03T04:32:32Z    ERROR   Workspace Controller    {"workspace": {"name":"playground","namespace":"dev"}, "msg": "reconcile workspace", "error": "ssh key ID was not found for ssh key name \"git-terraform\""}

### Output of relevant `kubectl` commands

kubectl apply -f workspace-demo2.yaml
workspace.app.terraform.io/playground configured

### Expected Behavior
What should have happened?
The SSHkey should be selected for the new Workspace, no error in k8s logs.

### Actual Behavior
What actually happened?
Error in k8s logs, workspace is created, but the workspaces CRD doc does not get a updated status:

### Additional Context
We can see the sshKey in TF cloud, and even select it from drop down if we create workspace without the sshKey option.

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Comment by arybolovlev** [comment]
Hi @diepes,

Thank you for reporting this issue. I would like to ask you to share additional information to better understand the issue.

In your bash terminal do the following steps:

- Export the token(the one that you use with the operator) and your organization name to environment variables `TFC_TOKEN` and `TFC_ORG`, respectively:

```console
$ export TFC_TOKEN=QjoMjunScDZWayg.atlasv1.KLJHSDflgkasdhgflkasdfhglasdfghlsdf
$ export TFC_ORG=your-org-name
```

- Get the list of SSH Key that belong to your org:

```console
$ curl \
  --header "Authorization: Bearer $TFC_TOKEN" \
  https://app.terraform.io/api/v2/organizations/$TFC_ORG/ssh-keys
...
{"data":[{"id":"sshkey-2NHeLdyqgDpbKfCf","type":"ssh-keys","attributes":{"name":"removeMe"},"links":{"self":"/api/v2/ssh-keys/sshkey-2NHeLdyqgDpbKfCf"}}]}
```

- If possible, share the output. If not, please let me know if you can see there the SSH key name you have configured in your YAML manifest. Would be great if you can copy it from the output and paste it to the YAML manifest to make sure they are identical. Let me know if that works.

- The above output contains the SSH key ID: `sshkey-2NHeLdyqgDpbKfCf`. As a second option, I would like to ask you to replace `spec.sshKey.name` with `spec.sshKey.id`(it should be either of them, but not both) and use the ID from the output. Let me know if that works.

Thank you.

**Comment by diepes** [comment]
@arybolovlev thank for the help.

Got the issue resolved. The token we used must not have had enough permission to see the ssh-keys.

It returned empty list for the curl above.

Issue resolved after using a new token with more permissions.

Thanks for the help, the operator seem to be working great.
