### ISSUE TITLE
🤔 Documenting pre-requisites for controlling team access

### ISSUE THREAD

**Issue by NZTimKeegan** [hashicorp/terraform-cloud-operator#333]
### Operator Version, Kind and Kubernetes Version
 - Operator version: 2.0.0-beta8
 - Kind: Workspace
 - Kubernetes version: n/a

### YAML Manifest File

```yaml
n/a
```

### Output Log

n/a

### Kubectl Outputs

n/a

### Question

I recently discovered the token I was using was failing to assign team access to workspaces. I landed on two possible ways to solve the problem:

1. Make the account used by the operator a member of every team
2. Set all the teams visibility to "organization"

We went with option 2 because it felt like less work, and it did solve the problem. My question is: would it help to make this apparent somewhere in the docs? I'm happy to contribute the change but I'm unsure where to start

### References

n/a

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Comment by sheneska** [comment]
Hi @NZTimKeegan, thank you for opening this! A good place to add this would be [here](https://developer.hashicorp.com/terraform/cloud-docs/users-teams-organizations/teams). Feel free to drop any further questions. Thanks for contributing.
