### ISSUE TITLE
Migrating from v1 to v2 operator - module variables referencing workspace variables?

### ISSUE THREAD

**Issue by nabadger** [hashicorp/terraform-cloud-operator#409]
### Operator Version, Kind and Kubernetes Version
 - Operator version: v1 to v2
 - Kind: Workspace | Module
 - Kubernetes version: 1.27

### YAML Manifest File

```yaml
N/A
```

### Question

I'm migrating from the k8s v1 operator to the newer v2 operator. 

In the existing v1 operator we define a single `Workspace` CR with all of our variables.

In the v2 operator we define a `Workspace` CR with variables, but it also looks like we have to specify those variables in the `Module` CR as well.

This seems like we're duplicating some references here, vs say "use all the variables defined in the `Workspace`.

I just wanted to clarify if I'm using this correctly - i.e. is it right that I duplicate the variable names?

Thanks!

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Comment by arybolovlev** [comment]
Hi @nabadger,

This is not a duplicate, but a reference. The Module controller implements API-driven workflow and it requires specifying which variables defined in a workspace will be used.

Thanks!

**Comment by nabadger** [comment]
Thanks - makes sense to me now.
