### ISSUE TITLE
Add documentation for v1 to v2 migration with regards to module name change

### ISSUE THREAD

**Issue by nabadger** [hashicorp/terraform-cloud-operator#410]
### Description

We are attempting to migrate to from the v1 to the v2 operator. We noticed that when having a new `Module` CR referencing an existing resource (created by the v1 `Workspace`), we run into the following error:

![provider-error](https://github.com/hashicorp/terraform-cloud-operator/assets/28828562/04448104-6738-443e-9bbb-8dfaede33651)

In the existing (v1) state file the module is named `module.operator`, where as in v2 it defaults to `module.this`.

This is configurable as per: https://github.com/hashicorp/terraform-cloud-operator/pull/172 but took a bit of while to find. 

It would be good to document this in the migration docs (assuming we did the right thing).

### Potential YAML Configuration

In our case we had to set the module name to `operator`, so that it generates `module.operator` as previous.

```yaml
apiVersion: app.terraform.io/v1alpha2
kind: Module
spec:
  name: operator
...
```

### Community Note

* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Comment by arybolovlev** [comment]
Hi @nabadger,

Thank you for bringing our attention here. There are a few things that are currently missing in the migration guide and I am working on updating it. The Module name is one of the things that will be added.

Let's keep this issue open until an updated guide is available.

Thanks!
