### ISSUE TITLE
🚀 Module shouldn't always auto-apply

### ISSUE THREAD

**Issue by mottetm** [hashicorp/terraform-cloud-operator#83]
Hi team!

Great to see the work you guys are doing here, it really fixes some of the issues I was having with the first iteration of the operator. I was playing around with the new modules to see how it behaves and noticed that [it will auto apply the runs](https://github.com/hashicorp/terraform-cloud-operator/blob/main/controllers/module_controller.go#L468), regardless of the workspace settings. Any reason behind that choice? It seems to me that it would make more sense to rely on the behavior that the workspace defines.

Looking forward to more awesomeness in this project 😃

**Comment by arybolovlev** [comment]
Hi @mottetm,

Thank you for the valuable feedback!

This behavior was inherited from the first version of the operator and there it was driven by the fact that a Workspace always has auto-apply enabled. We have received a lot of feedback to make it configurable and we made that for the Workspaces. However, a new controller `Module` that implements API-driven run workflow remained auto-applied. I agree with you -- this is something that we need to change and I want to let you know that there is a task for this change. I did a quick change and looks like this is one line change only. Basically, we need to rid of auto-apply in the `Module` and rely on the Workspace settings.

I have one concern here. Right now, the controller generates and uploads Terraform code, once the upload is successful, it triggers a new run and then checks every 30 seconds the run status. When the Run hits one of the finite states, the controller reports the success status for the CR and it won't be required. It means that next time the controller will proceed with this CR when it gets updated or over the sync period. If we remove auto-apply now and a Workspace has a `manual` approval method, then CR will stay in the queue waiting for action. In this case, the controller will keep checking the Run status every 30 seconds. Potentially, it can take hours(for someone to approve or discard the run) and it means that the controller is going to do unnecessary API calls. In the end, it can affect performance.

The 30 seconds check interval is not configurable at the moment and is not ideal. In some cases, it can take dozen minutes to apply a module and all this time the controller is going to do checks. Right now, I would call it a trade-off. Also, we cannot guarantee to check every 30 seconds, in certain scenarios it takes longer.

With all that being said, I think we still can do this change and update FAQ/Documentation with more details to make everyone aware.

I hope you will continue using this Operator and give us more feedback while we polish it for GA. 😊

Thank you again! 👍🏻
